[project]
name = "kuerten"
description = "Create a project from scratch: Start from a blank scaffold for your next Clarity contract"
authors = []
telemetry = true
cache_dir = "./.cache"

# [contracts.kuerten]
# path = "contracts/kuerten.clar"

[[project.requirements]]
contract_id = 'SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE.sip-010-trait-ft-standard'

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
